package com.rabbithole.musicbbit.presentation.settings

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.rabbithole.musicbbit.domain.model.ScanDirectory
import com.rabbithole.musicbbit.domain.usecase.AddScanDirectoryUseCase
import com.rabbithole.musicbbit.domain.usecase.GetScanDirectoriesUseCase
import com.rabbithole.musicbbit.domain.usecase.RemoveScanDirectoryUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.io.File
import javax.inject.Inject

sealed interface ScanDirectorySettingsUiState {
    data object Loading : ScanDirectorySettingsUiState
    data class Success(
        val directories: List<ScanDirectory>,
        val directoryCount: Int = 0,
        val lastScanTime: String? = null,
        val showAddDialog: Boolean = false,
        val addError: String? = null
    ) : ScanDirectorySettingsUiState
}

sealed interface ScanDirectorySettingsAction {
    data object OnAddDirectory : ScanDirectorySettingsAction
    data class OnRemoveDirectory(val id: Long) : ScanDirectorySettingsAction
    data object OnBack : ScanDirectorySettingsAction
    data object OnDismissDialog : ScanDirectorySettingsAction
    data class OnDirectoryPathSubmitted(val path: String) : ScanDirectorySettingsAction
}

@HiltViewModel
class ScanDirectorySettingsViewModel @Inject constructor(
    private val getScanDirectoriesUseCase: GetScanDirectoriesUseCase,
    private val addScanDirectoryUseCase: AddScanDirectoryUseCase,
    private val removeScanDirectoryUseCase: RemoveScanDirectoryUseCase
) : ViewModel() {

    private val _uiState = MutableStateFlow<ScanDirectorySettingsUiState>(ScanDirectorySettingsUiState.Loading)
    val uiState: StateFlow<ScanDirectorySettingsUiState> = _uiState.asStateFlow()

    init {
        observeDirectories()
    }

    private fun observeDirectories() {
        getScanDirectoriesUseCase()
            .onEach { directories ->
                _uiState.update { currentState ->
                    if (currentState is ScanDirectorySettingsUiState.Success) {
                        currentState.copy(directories = directories)
                    } else {
                        ScanDirectorySettingsUiState.Success(
                            directories = directories,
                            directoryCount = directories.size
                        )
                    }
                }
            }
            .launchIn(viewModelScope)
    }

    fun onAction(action: ScanDirectorySettingsAction) {
        when (action) {
            is ScanDirectorySettingsAction.OnAddDirectory -> {
                _uiState.update {
                    if (it is ScanDirectorySettingsUiState.Success) {
                        it.copy(showAddDialog = true, addError = null)
                    } else {
                        it
                    }
                }
            }

            is ScanDirectorySettingsAction.OnRemoveDirectory -> {
                viewModelScope.launch {
                    removeScanDirectoryUseCase(action.id)
                }
            }

            is ScanDirectorySettingsAction.OnBack -> {
                // Navigation is handled in the UI layer
            }

            is ScanDirectorySettingsAction.OnDismissDialog -> {
                _uiState.update {
                    if (it is ScanDirectorySettingsUiState.Success) {
                        it.copy(showAddDialog = false, addError = null)
                    } else {
                        it
                    }
                }
            }

            is ScanDirectorySettingsAction.OnDirectoryPathSubmitted -> {
                addDirectory(action.path)
            }
        }
    }

    private fun addDirectory(path: String) {
        viewModelScope.launch {
            val file = File(path)
            if (!file.exists() || !file.isDirectory) {
                _uiState.update {
                    if (it is ScanDirectorySettingsUiState.Success) {
                        it.copy(addError = "Invalid directory path")
                    } else {
                        it
                    }
                }
                return@launch
            }

            val directory = ScanDirectory(
                id = 0, // Auto-generated by Room
                path = path,
                name = file.name,
                addedAt = System.currentTimeMillis()
            )

            val result = addScanDirectoryUseCase(directory)
            if (result.isSuccess) {
                _uiState.update {
                    if (it is ScanDirectorySettingsUiState.Success) {
                        it.copy(showAddDialog = false, addError = null)
                    } else {
                        it
                    }
                }
            } else {
                _uiState.update {
                    if (it is ScanDirectorySettingsUiState.Success) {
                        it.copy(addError = "Failed to add directory")
                    } else {
                        it
                    }
                }
            }
        }
    }
}
